In [1]:
import numpy as np

In [ ]:
meu_array = np.arange(1_000_000)

In [ ]:
meu_array

In [ ]:
meu_lista = list(range(1_000_000))

In [ ]:
meu_lista

In [ ]:
%time for _ in range(10): meu_lista2 = [x * 2 for x in meu_lista]

In [ ]:
%time for _ in range(10): meu_array2 = meu_array * 2

## Array Multidimensional

In [ ]:
data = np.random.randn(2,3)

In [ ]:
data

In [ ]:
data * 10

In [ ]:
data.shape

In [ ]:
data.dtype

## Criando ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0]

In [ ]:
arr1 = np.array(data1)

In [ ]:
arr1

In [ ]:
arr1.shape

In [ ]:
arr1.dtype

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr2 = np.array(data2)

In [ ]:
arr2

In [ ]:
arr2.ndim

In [ ]:
arr2.shape

In [ ]:
arr2.dtype

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
meu_zeros = np.zeros((3,6), dtype=np.int64)

In [11]:
meu_zeros.dtype

dtype('int64')

In [12]:
meu_zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
meu_vazio = np.empty((2, 3, 2))

In [15]:
meu_vazio

array([[[6.94365984e-310, 2.62380557e-316],
        [0.00000000e+000, 0.00000000e+000],
        [6.94338243e-310, 1.03140915e-071]],

       [[2.87831884e+180, 3.50745242e-033],
        [5.40127634e-062, 3.92904994e-061],
        [6.23177136e+174, 6.56348696e+169]]])

In [16]:
meu_vazio.dtype

dtype('float64')

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Type para ndarrays

In [20]:
arr1 = np.array([1,2,1], dtype=np.float64)

In [21]:
arr2 = np.array([1,2,1], dtype=np.int64)

In [22]:
arr1

array([1., 2., 1.])

In [23]:
arr2

array([1, 2, 1])

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

In [26]:
arr = np.array([1,2,3,4,5])

In [27]:
arr.dtype

dtype('int64')

In [28]:
arr_float = arr.astype(np.float64)

In [29]:
arr_float

array([1., 2., 3., 4., 5.])

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [33]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
arr.dtype

dtype('float64')

In [36]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [37]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [41]:
numeric = numeric_string.astype(float)

In [42]:
numeric

array([ 1.25, -9.6 , 42.  ])

In [43]:
numeric.dtype

dtype('float64')

In [44]:
int_array = np.arange(10)

In [45]:
calibres = np.array([.22, .270, .357, .380])

In [46]:
int_array.astype(calibres.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Aritméticas com NumPy Array

In [51]:
arr1 = np.array([[1.,2,3], [4,5,6]])

In [53]:
arr2 = np.array([[7.,8,9], [10,11,12]])

In [54]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [56]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [57]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [58]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [62]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [63]:
arr1 * 9

array([[ 9., 18., 27.],
       [36., 45., 54.]])

In [64]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [69]:
arr3 = np.array([[0.,2,1], [4,2,12]])

In [70]:
arr3

array([[ 0.,  2.,  1.],
       [ 4.,  2., 12.]])

In [72]:
arr1[arr3 == arr1]

array([2., 4.])

In [77]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr3d[0][0]

array([1, 2, 3])

In [81]:
arr3d[0][0][0]

1

In [82]:
arr3d[0,0,0]

1

In [83]:
arr3d[0,0]

array([1, 2, 3])

In [89]:
arr3d[:, :, 2]

array([[ 3,  6],
       [ 9, 12]])

In [87]:
arr3d[1, :, 1:]

array([[ 8,  9],
       [11, 12]])